# **Child Well-being - Data Extractor**<br/>
**University: University of Milano-Bicocca**<br/>
**Master's Degree: Data Science (A.Y. 2025/2026)**<br/>
**Course: Data Science Lab**<br/>

In [1]:
from io import StringIO

import requests
import polars as pl

In [2]:
# Define API query URL (CSV with labels format)
url = 'https://sdmx.oecd.org/public/rest/data/OECD.WISE.CWB,DSD_CWB@DF_CWB,/all?dimensionAtObservation=AllDimensions&format=csvfile'
# Fetch data
response = requests.get(url)

# Load into polars DataFrame
df = pl.read_csv(StringIO(response.text))

In [3]:
# Filters from a preliminary analysis of missing values and data availability across dimensions, measures, countries, and years

## Keep only the measures with the lowest number of missing values for the years 2009,2012,2015,2018
measures = [
    'A1_2','A1_4',                              # Material conditions
    'A2_1',                                     # Physical health conditions
    'A3_3','A3_4','A3_5',                       # Cognitive & educational outcome
    'A4_6',                                     # Social & emotional outcome
    'B1_1','B1_5',                              # Home & Family Life
    'B2_1','B2_4','B2_5',                       # Life at school & early education and care
    'B3_5',                                     # Social Life and life in the community
    'B4_3',                                     # Online life
    'C1_1','C1_2','C1_3','C1_4','C1_5',         # Family policies
    'C2_1','C2_2','C2_3',                       # House & Community policies
    'C3_1','C3_2','C3_3',                       # Health policies
    'C4_1','C4_2','C4_3','C4_4','C4_5','C4_6',  # Education & early childhood policies
    'C5_1',                                     # Environmental policies
]

## Keep only the European countries
areas = [
    'SWE', 'DNK', 'NOR', 'FIN', 'ISL', 'LTU', 'LVA', 'EST',        # Northern Europe
    'IRL', 'GBR', 'NLD', 'BEL', 'FRA', 'LUX', 'CHE', 'AUT', 'DEU', # Western Europe
    'ESP', 'PRT', 'ITA', 'GRC', 'SVN', 'HRV', 'TUR',               # Southern Europe
    'POL', 'CZE', 'SVK', 'HUN', 'ROU', 'BGR',                      # Eastern Europe
]

## Keep only a subset of years
years = [2009, 2012, 2015, 2018]

In [4]:
# Apply the filters on the dataframe
df = df.filter(
    pl.col('MEASURE').is_in(measures) &
    pl.col('REF_AREA').is_in(areas) &
    pl.col('TIME_PERIOD').is_in(years)
)

In [5]:
df.head(10)

shape: (10, 12)
┌───────────────┬──────────┬─────────┬────────┬───┬──────────────┬──────────┬──────────┬───────────┐
│ DATAFLOW      ┆ REF_AREA ┆ MEASURE ┆ DOMAIN ┆ … ┆ UNIT_MEASURE ┆ BASE_PER ┆ DECIMALS ┆ POP_GROUP │
│ ---           ┆ ---      ┆ ---     ┆ ---    ┆   ┆ ---          ┆ ---      ┆ ---      ┆ ---       │
│ str           ┆ str      ┆ str     ┆ str    ┆   ┆ str          ┆ i64      ┆ i64      ┆ str       │
╞═══════════════╪══════════╪═════════╪════════╪═══╪══════════════╪══════════╪══════════╪═══════════╡
│ OECD.WISE.CWB ┆ AUT      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ AUT      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ AUT      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ AUT      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ BEL      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ BEL      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ BEL      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ BEL      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ CZE      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ OECD.WISE.CWB ┆ CZE      ┆ C2_1    ┆ C2     ┆ … ┆ USD_PPP      ┆ 2015     ┆ 1        ┆ _Z        │
│ :DSD_CWB@DF_C ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
│ WB(1…         ┆          ┆         ┆        ┆   ┆              ┆          ┆          ┆           │
└───────────────┴──────────┴─────────┴────────┴───┴──────────────┴──────────┴──────────┴───────────┘

In [6]:
# Create a grid with all the combinations of area and time period
df_grid = pl.DataFrame()

years = df.select('TIME_PERIOD').unique().to_series().to_list()

for area in areas:
    for year in years:
        df_grid = df_grid.vstack(
            pl.DataFrame(
                {
                    'REF_AREA': area,
                    'TIME_PERIOD': year,
                }
            )
        )

#Populate the grid with the measures in a wide format
for measure in measures:
    df_temp = df.filter(
        pl.col('MEASURE') == measure
    ).select(
        ['REF_AREA', 'TIME_PERIOD', 'OBS_VALUE']
    ).with_columns(
        pl.col('OBS_VALUE').alias(measure)
    ).select(
        ['REF_AREA', 'TIME_PERIOD', measure]
    )
    df_grid = df_grid.join(
        df_temp,
        on=['REF_AREA', 'TIME_PERIOD'],
        how='left'
    )

In [7]:
df_grid.head(10)

shape: (10, 34)
┌──────────┬─────────────┬──────┬──────┬───┬─────────┬────────┬──────┬───────┐
│ REF_AREA ┆ TIME_PERIOD ┆ A1_2 ┆ A1_4 ┆ … ┆ C4_4    ┆ C4_5   ┆ C4_6 ┆ C5_1  │
│ ---      ┆ ---         ┆ ---  ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---  ┆ ---   │
│ str      ┆ i64         ┆ f64  ┆ f64  ┆   ┆ f64     ┆ f64    ┆ f64  ┆ f64   │
╞══════════╪═════════════╪══════╪══════╪═══╪═════════╪════════╪══════╪═══════╡
│ SWE      ┆ 2015        ┆ 4.4  ┆ 1.7  ┆ … ┆ 11581.8 ┆ 1220.3 ┆ 13.4 ┆ 208.7 │
│ SWE      ┆ 2018        ┆ 5.0  ┆ 1.0  ┆ … ┆ 12368.5 ┆ 1254.5 ┆ 12.3 ┆ 252.8 │
│ SWE      ┆ 2012        ┆ 2.4  ┆ 0.7  ┆ … ┆ 11262.5 ┆ null   ┆ null ┆ 214.1 │
│ SWE      ┆ 2009        ┆ null ┆ 1.5  ┆ … ┆ 10602.2 ┆ null   ┆ null ┆ 204.8 │
│ DNK      ┆ 2015        ┆ 4.1  ┆ 0.5  ┆ … ┆ null    ┆ null   ┆ null ┆ 207.5 │
│ DNK      ┆ 2018        ┆ 4.1  ┆ 0.3  ┆ … ┆ 10140.2 ┆ 43.8   ┆ 11.3 ┆ 206.6 │
│ DNK      ┆ 2012        ┆ 2.8  ┆ 0.4  ┆ … ┆ 11820.4 ┆ null   ┆ null ┆ 189.9 │
│ DNK      ┆ 2009        ┆ null ┆ 1.1  ┆ … ┆ 12717.1 ┆ null   ┆ null ┆ 204.8 │
│ NOR      ┆ 2015        ┆ 0.8  ┆ 1.1  ┆ … ┆ 13993.4 ┆ 492.8  ┆ 9.9  ┆ 534.8 │
│ NOR      ┆ 2018        ┆ 0.9  ┆ 0.7  ┆ … ┆ 14383.3 ┆ 474.1  ┆ 9.6  ┆ 542.9 │
└──────────┴─────────────┴──────┴──────┴───┴─────────┴────────┴──────┴───────┘

In [8]:
df_grid.write_parquet('../data/010_child_well_being.parquet')

*This notebook is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).*